spring.application.name=nkap

spring.datasource.url=jdbc:postgresql://localhost:5432/nkapdb
spring.datasource.username=admin
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
