--
-- PostgreSQL database dump
--

-- Dumped from database version 18.6 (Ubuntu 18.6-1.pgdg22.04+2)
-- Dumped by pg_dump version 18.6 (Ubuntu 18.6-1.pgdg22.04+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.accounts (
    balance numeric(38,2) NOT NULL,
    app_user_id bigint NOT NULL,
    id bigint NOT NULL,
    account_type character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    financial_institution_id bigint,
    CONSTRAINT accounts_account_type_check CHECK (((account_type)::text = ANY ((ARRAY['CHECKING'::character varying, 'SAVINGS'::character varying, 'CASH'::character varying, 'CREDIT'::character varying])::text[])))
);


ALTER TABLE public.accounts OWNER TO admin;

--
-- Name: accounts_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

CREATE SEQUENCE public.accounts_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.accounts_seq OWNER TO admin;

--
-- Name: app_user; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.app_user (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL
);


ALTER TABLE public.app_user OWNER TO admin;

--
-- Name: app_user_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

CREATE SEQUENCE public.app_user_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.app_user_seq OWNER TO admin;

--
-- Name: authority; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.authority (
    app_user_id bigint,
    id bigint NOT NULL,
    authority_name character varying(255)
);


ALTER TABLE public.authority OWNER TO admin;

--
-- Name: authority_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

CREATE SEQUENCE public.authority_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.authority_seq OWNER TO admin;

--
-- Name: budget; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.budget (
    budget_year integer NOT NULL,
    app_user_id bigint NOT NULL,
    id bigint NOT NULL,
    budget_month character varying(255) NOT NULL,
    CONSTRAINT budget_budget_month_check CHECK (((budget_month)::text = ANY ((ARRAY['JANUARY'::character varying, 'FEBRUARY'::character varying, 'MARCH'::character varying, 'APRIL'::character varying, 'MAY'::character varying, 'JUNE'::character varying, 'JULY'::character varying, 'AUGUST'::character varying, 'SEPTEMBER'::character varying, 'OCTOBER'::character varying, 'NOVEMBER'::character varying, 'DECEMBER'::character varying])::text[])))
);


ALTER TABLE public.budget OWNER TO admin;

--
-- Name: budget_category; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.budget_category (
    allocation numeric(19,2) NOT NULL,
    budget_id bigint NOT NULL,
    category_id bigint NOT NULL,
    id bigint NOT NULL
);


ALTER TABLE public.budget_category OWNER TO admin;

--
-- Name: budget_category_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.budget_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.budget_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: budget_group; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.budget_group (
    is_default boolean NOT NULL,
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.budget_group OWNER TO admin;

--
-- Name: budget_group_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.budget_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.budget_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: budget_group_mapping; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.budget_group_mapping (
    budget_id bigint NOT NULL,
    group_id bigint NOT NULL
);


ALTER TABLE public.budget_group_mapping OWNER TO admin;

--
-- Name: budget_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.budget ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.budget_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: budget_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

CREATE SEQUENCE public.budget_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.budget_seq OWNER TO admin;

--
-- Name: category; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.category (
    balance numeric(19,2) NOT NULL,
    group_id bigint NOT NULL,
    id bigint NOT NULL,
    name character varying(100) NOT NULL
);


ALTER TABLE public.category OWNER TO admin;

--
-- Name: category_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: financial_institution; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.financial_institution (
    id bigint NOT NULL,
    display_name character varying(255) NOT NULL,
    institution_key character varying(255) NOT NULL
);


ALTER TABLE public.financial_institution OWNER TO admin;

--
-- Name: financial_institution_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.financial_institution ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.financial_institution_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transactions; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.transactions (
    amount numeric(19,2) NOT NULL,
    transaction_date date NOT NULL,
    account_id bigint,
    budget_category_id bigint,
    budget_id bigint NOT NULL,
    id bigint NOT NULL,
    description character varying(100),
    note character varying(500),
    direction character varying(255) NOT NULL,
    transaction_type character varying(255) NOT NULL,
    transfer_id uuid,
    CONSTRAINT transactions_direction_check CHECK (((direction)::text = ANY ((ARRAY['DEBIT'::character varying, 'CREDIT'::character varying])::text[]))),
    CONSTRAINT transactions_transaction_type_check CHECK (((transaction_type)::text = ANY ((ARRAY['STANDARD'::character varying, 'ADJUSTMENT'::character varying, 'TRANSFER'::character varying])::text[])))
);


ALTER TABLE public.transactions OWNER TO admin;

--
-- Name: transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);


--
-- Name: app_user app_user_email_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_email_key UNIQUE (email);


--
-- Name: app_user app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);


--
-- Name: authority authority_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.authority
    ADD CONSTRAINT authority_pkey PRIMARY KEY (id);


--
-- Name: budget budget_app_user_id_budget_month_budget_year_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.budget
    ADD CONSTRAINT budget_app_user_id_budget_month_budget_year_key UNIQUE (app_user_id, budget_month, budget_year);


--
-- Name: budget_category budget_category_budget_id_category_id_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.budget_category
    ADD CONSTRAINT budget_category_budget_id_category_id_key UNIQUE (budget_id, category_id);


--
-- Name: budget_category budget_category_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.budget_category
    ADD CONSTRAINT budget_category_pkey PRIMARY KEY (id);


--
-- Name: budget_group_mapping budget_group_mapping_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.budget_group_mapping
    ADD CONSTRAINT budget_group_mapping_pkey PRIMARY KEY (budget_id, group_id);


--
-- Name: budget_group budget_group_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.budget_group
    ADD CONSTRAINT budget_group_pkey PRIMARY KEY (id);


--
-- Name: budget budget_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.budget
    ADD CONSTRAINT budget_pkey PRIMARY KEY (id);


--
-- Name: category category_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (id);


--
-- Name: financial_institution financial_institution_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.financial_institution
    ADD CONSTRAINT financial_institution_pkey PRIMARY KEY (id);


--
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);


--
-- Name: budget uk8es9jye5xa2d6heeqdb7x0wkr; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.budget
    ADD CONSTRAINT uk8es9jye5xa2d6heeqdb7x0wkr UNIQUE (app_user_id, budget_month, budget_year);


--
-- Name: financial_institution ukkee5inctopfy37nq8humjrufj; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.financial_institution
    ADD CONSTRAINT ukkee5inctopfy37nq8humjrufj UNIQUE (institution_key);


--
-- Name: budget_category ukmu7iafcodijhkxdfm3220um31; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.budget_category
    ADD CONSTRAINT ukmu7iafcodijhkxdfm3220um31 UNIQUE (budget_id, category_id);


--
-- Name: transactions fk20w7wsg13u9srbq3bd7chfxdh; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fk20w7wsg13u9srbq3bd7chfxdh FOREIGN KEY (account_id) REFERENCES public.accounts(id);


--
-- Name: category fk4tolgdwd88ktw1lixmvxtanos; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT fk4tolgdwd88ktw1lixmvxtanos FOREIGN KEY (group_id) REFERENCES public.budget_group(id);


--
-- Name: budget_group_mapping fk8ygenbly634xa83chv6gm60jn; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.budget_group_mapping
    ADD CONSTRAINT fk8ygenbly634xa83chv6gm60jn FOREIGN KEY (budget_id) REFERENCES public.budget(id);


--
-- Name: transactions fk9y9ibkogh2ubuww94gl10sr1r; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fk9y9ibkogh2ubuww94gl10sr1r FOREIGN KEY (budget_id) REFERENCES public.budget(id);


--
-- Name: budget fka5iv73ejpbu2y5ypmo2wnns5r; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.budget
    ADD CONSTRAINT fka5iv73ejpbu2y5ypmo2wnns5r FOREIGN KEY (app_user_id) REFERENCES public.app_user(id);


--
-- Name: accounts fkgwkxr90ueqc7trvrqgn1ht6rq; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT fkgwkxr90ueqc7trvrqgn1ht6rq FOREIGN KEY (financial_institution_id) REFERENCES public.financial_institution(id);


--
-- Name: budget_group_mapping fkm4j60w3abg1osj1yrff6p6cfx; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.budget_group_mapping
    ADD CONSTRAINT fkm4j60w3abg1osj1yrff6p6cfx FOREIGN KEY (group_id) REFERENCES public.budget_group(id);


--
-- Name: transactions fko81t9b647xm8l1qjg935k1ohr; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fko81t9b647xm8l1qjg935k1ohr FOREIGN KEY (budget_category_id) REFERENCES public.budget_category(id);


--
-- Name: authority fkomyn7ph69bv9ycakmbkmbniy3; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.authority
    ADD CONSTRAINT fkomyn7ph69bv9ycakmbkmbniy3 FOREIGN KEY (app_user_id) REFERENCES public.app_user(id);


--
-- Name: budget_category fkosa9i1lxo3j8v3reheus8gubg; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.budget_category
    ADD CONSTRAINT fkosa9i1lxo3j8v3reheus8gubg FOREIGN KEY (budget_id) REFERENCES public.budget(id);


--
-- Name: budget_category fkqdqowarwbu2pjpi5i0bq6klcq; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.budget_category
    ADD CONSTRAINT fkqdqowarwbu2pjpi5i0bq6klcq FOREIGN KEY (category_id) REFERENCES public.category(id);


--
-- Name: accounts fkwrvud8ayhngl6d75q4ityyu9; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT fkwrvud8ayhngl6d75q4ityyu9 FOREIGN KEY (app_user_id) REFERENCES public.app_user(id);


--
-- PostgreSQL database dump complete
--
